[package]
name = "netsecrets"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.3.24", features = ["derive"] }
ipnetwork = "0.21.1"
aes-gcm = "0.10"
rsa = { version = "0.9", features = ["pem"] }
ed25519-dalek = { version = "2.0", features = ["rand_core"] }
x25519-dalek = { version = "2.0", features = ["static_secrets"] }
sha2 = "0.10"
rand = "0.8"
base64 = "0.21"
hex = "0.4"

[dependencies.tokio]
version = "1.0"
features = ["full"]
optional = true

[features]
default = []
async = ["tokio"]